on: 
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    if: success()
    steps:
    - name: Trigger Jenkins Build
      uses: actions/checkout@v2
      with:
        jenkins-url: 'http://52.14.62.107:8080/'
        jenkins-user: 'admin'
        jenkins-token: ${{ secrets.MYTOKEN }}
        job-name: 'mul-br'
        add-build-url-to-check-run: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

