name: Status Check
on: [pull_request]
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Jenkins build
      with:
         jenkins-url: 'http://52.14.62.107:8080/'
         token: ${{ secrets.mytoken }}
         job-name: 'mul-br'
         
      
    
    
