name: Status Check
on: [pull_request]
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Jenkins build
      uses: jenkins-actions/jenkins-build@v2
      with:
         jenkins-url: 'http://52.14.62.107:8080/'
         job-name: 'mul-br'
         
      
    
    
